//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSCADA.CommonUI{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSCADA.Common.Schema.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver.
        /// </summary>
        public static string ArchiverItemName {
            get {
                return ResourceManager.GetString("ArchiverItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot; &gt;
        ///      &lt;Viewbox&gt;
        ///        &lt;Border BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;#FF0000FF&quot; Name=&quot;bdr&quot;&gt;
        ///          &lt;StackPanel Orientation=&quot;Vertical&quot;&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Name}&quot; Name=&quot;txt1&quot; Margin=&quot;0,0,10,0&quot; ToolTip=&quot;{Binding Path=Type}&quot; /&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Value}&quot; Name=&quot;txt2&quot; Margi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChannelDefaultTemplate {
            get {
                return ResourceManager.GetString("ChannelDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels Tree.
        /// </summary>
        public static string ChannelsItemName {
            get {
                return ResourceManager.GetString("ChannelsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox Tool.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to FreeSCADA web site to look for newer versions.
        /// </summary>
        public static string CommandCheckForUpdatesDescription {
            get {
                return ResourceManager.GetString("CommandCheckForUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string CommandCheckForUpdatesName {
            get {
                return ResourceManager.GetString("CommandCheckForUpdatesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate with data....
        /// </summary>
        public static string CommandCommonBindingName {
            get {
                return ResourceManager.GetString("CommandCommonBindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string CommandContextHelp {
            get {
                return ResourceManager.GetString("CommandContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CommandCopyDescription {
            get {
                return ResourceManager.GetString("CommandCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CommandCopyName {
            get {
                return ResourceManager.GetString("CommandCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to clipboard.
        /// </summary>
        public static string CommandCutDescription {
            get {
                return ResourceManager.GetString("CommandCutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CommandCutName {
            get {
                return ResourceManager.GetString("CommandCutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group selected items.
        /// </summary>
        public static string CommandGroupDescription {
            get {
                return ResourceManager.GetString("CommandGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string CommandGroupName {
            get {
                return ResourceManager.GetString("CommandGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string CommandPasteDescription {
            get {
                return ResourceManager.GetString("CommandPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string CommandPasteName {
            get {
                return ResourceManager.GetString("CommandPasteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string CommandRedoDescription {
            get {
                return ResourceManager.GetString("CommandRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string CommandRedoName {
            get {
                return ResourceManager.GetString("CommandRedoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string CommandUndoDescription {
            get {
                return ResourceManager.GetString("CommandUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string CommandUndoName {
            get {
                return ResourceManager.GetString("CommandUndoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove grouping from curently selected item.
        /// </summary>
        public static string CommandUngroupDescription {
            get {
                return ResourceManager.GetString("CommandUngroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnGroup.
        /// </summary>
        public static string CommandUngroupName {
            get {
                return ResourceManager.GetString("CommandUngroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate syntax of active script.
        /// </summary>
        public static string CommandValidateDescription {
            get {
                return ResourceManager.GetString("CommandValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check syntax.
        /// </summary>
        public static string CommandValidateName {
            get {
                return ResourceManager.GetString("CommandValidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XAML code of current document.
        /// </summary>
        public static string CommandXamlViewDescription {
            get {
                return ResourceManager.GetString("CommandXamlViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML representation.
        /// </summary>
        public static string CommandXamlViewName {
            get {
                return ResourceManager.GetString("CommandXamlViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the object to the back of the schema.
        /// </summary>
        public static string CommandZMoveBottomDescription {
            get {
                return ResourceManager.GetString("CommandZMoveBottomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To back.
        /// </summary>
        public static string CommandZMoveBottomName {
            get {
                return ResourceManager.GetString("CommandZMoveBottomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the object to the front of the schema.
        /// </summary>
        public static string CommandZMoveTopDescription {
            get {
                return ResourceManager.GetString("CommandZMoveTopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To front.
        /// </summary>
        public static string CommandZMoveTopName {
            get {
                return ResourceManager.GetString("CommandZMoveTopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string CommandZoomDescription {
            get {
                return ResourceManager.GetString("CommandZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string CommandZoomInDescription {
            get {
                return ResourceManager.GetString("CommandZoomInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string CommandZoomInName {
            get {
                return ResourceManager.GetString("CommandZoomInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string CommandZoomName {
            get {
                return ResourceManager.GetString("CommandZoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string CommandZoomOutDescription {
            get {
                return ResourceManager.GetString("CommandZoomOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string CommandZoomOutName {
            get {
                return ResourceManager.GetString("CommandZoomOutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vector graphics (*.xaml;*.svg)|*.xaml;*.svg|XAML  files (*.xaml)|*.xaml|svg files (*.svg)|*.svg|All files (*.*)|*.*.
        /// </summary>
        public static string FileImportDialogFilter {
            get {
                return ResourceManager.GetString("FileImportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeSCADA 2 files (*.fs2)|*.fs2|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenDialogFilter {
            get {
                return ResourceManager.GetString("FileOpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select trajectory object 
        ///    (line,rectangle,ellipse).
        /// </summary>
        public static string HelperSelectingToolTooltip {
            get {
                return ResourceManager.GetString("HelperSelectingToolTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string MainWindowName {
            get {
                return ResourceManager.GetString("MainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - Designer.
        /// </summary>
        public static string MainWindowNameEx {
            get {
                return ResourceManager.GetString("MainWindowNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to numeric value.
        /// </summary>
        public static string NumericBindingPanelName {
            get {
                return ResourceManager.GetString("NumericBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric expression binding.
        /// </summary>
        public static string NumExpressionBindingPanelName {
            get {
                return ResourceManager.GetString("NumExpressionBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media files|*.gif;*.BMP;*.PNG;*.JPEG;*.JPG;*.TIFF|All files (*.*)|*.*.
        /// </summary>
        public static string OpenMediaDialogFilter {
            get {
                return ResourceManager.GetString("OpenMediaDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ProjectContextMenuOpen {
            get {
                return ResourceManager.GetString("ProjectContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ProjectContextMenuRemove {
            get {
                return ResourceManager.GetString("ProjectContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ProjectContextMenuRename {
            get {
                return ResourceManager.GetString("ProjectContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        public static string SchemasItemName {
            get {
                return ResourceManager.GetString("SchemasItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string ScriptsItemName {
            get {
                return ResourceManager.GetString("ScriptsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Color Binding.
        /// </summary>
        public static string SolidColorBindingPanelName {
            get {
                return ResourceManager.GetString("SolidColorBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to string value.
        /// </summary>
        public static string StringBindingPanelName {
            get {
                return ResourceManager.GetString("StringBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two way string to value binding.
        /// </summary>
        public static string StringValueBindingPanelName {
            get {
                return ResourceManager.GetString("StringValueBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox Tool.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Edit Tool.
        /// </summary>
        public static string ToolActionEdit {
            get {
                return ResourceManager.GetString("ToolActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Tool.
        /// </summary>
        public static string ToolButton {
            get {
                return ResourceManager.GetString("ToolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Tool.
        /// </summary>
        public static string ToolChart {
            get {
                return ResourceManager.GetString("ToolChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentControl Tool.
        /// </summary>
        public static string ToolContentControl {
            get {
                return ResourceManager.GetString("ToolContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls Tools.
        /// </summary>
        public static string ToolControlsGroupName {
            get {
                return ResourceManager.GetString("ToolControlsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Tools.
        /// </summary>
        public static string ToolEditorGroupName {
            get {
                return ResourceManager.GetString("ToolEditorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse Tool.
        /// </summary>
        public static string ToolEllipse {
            get {
                return ResourceManager.GetString("ToolEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Tools.
        /// </summary>
        public static string ToolGrphicsGroupName {
            get {
                return ResourceManager.GetString("ToolGrphicsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ToolImageControl {
            get {
                return ResourceManager.GetString("ToolImageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon Tool.
        /// </summary>
        public static string ToolPolygon {
            get {
                return ResourceManager.GetString("ToolPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline Tool.
        /// </summary>
        public static string ToolPolyline {
            get {
                return ResourceManager.GetString("ToolPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBar Tool.
        /// </summary>
        public static string ToolProgressbar {
            get {
                return ResourceManager.GetString("ToolProgressbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Tool.
        /// </summary>
        public static string ToolRectangle {
            get {
                return ResourceManager.GetString("ToolRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollBar Tool.
        /// </summary>
        public static string ToolScrollbar {
            get {
                return ResourceManager.GetString("ToolScrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Tool.
        /// </summary>
        public static string ToolSelection {
            get {
                return ResourceManager.GetString("ToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Tool.
        /// </summary>
        public static string ToolSlider {
            get {
                return ResourceManager.GetString("ToolSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox Tool.
        /// </summary>
        public static string ToolTextbox {
            get {
                return ResourceManager.GetString("ToolTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleButton.
        /// </summary>
        public static string ToolToggleButton {
            get {
                return ResourceManager.GetString("ToolToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {unsaved project file}.
        /// </summary>
        public static string UnsavedProjectName {
            get {
                return ResourceManager.GetString("UnsavedProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string UntitledSchema {
            get {
                return ResourceManager.GetString("UntitledSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script_.
        /// </summary>
        public static string UntitledScript {
            get {
                return ResourceManager.GetString("UntitledScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to connect to web site: {0}.
        /// </summary>
        public static string UpdatesFailToCheckForNewVersion {
            get {
                return ResourceManager.GetString("UpdatesFailToCheckForNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version of FreeSCADA.
        /// </summary>
        public static string UpdatesHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("UpdatesHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of FreeSCADA is available. Would you like to go to web site and download it?.
        /// </summary>
        public static string UpdatesNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdatesNewVersionAvailable", resourceCulture);
            }
        }
    }
}
