//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3074
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSCADA.CLServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelInfo", Namespace="http://schemas.datacontract.org/2004/07/FreeSCADA.CLServer")]
    public partial class ChannelInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FullIdField;
        
        private bool IsReadOnlyField;
        
        private string NameField;
        
        private string PluginIdField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullId
        {
            get
            {
                return this.FullIdField;
            }
            set
            {
                this.FullIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadOnly
        {
            get
            {
                return this.IsReadOnlyField;
            }
            set
            {
                this.IsReadOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginId
        {
            get
            {
                return this.PluginIdField;
            }
            set
            {
                this.PluginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelState", Namespace="http://schemas.datacontract.org/2004/07/FreeSCADA.CLServer")]
    public partial class ChannelState : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ModifyTimeField;
        
        private FreeSCADA.CLServer.ChannelStatusFlags StatusField;
        
        private string TypeField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyTime
        {
            get
            {
                return this.ModifyTimeField;
            }
            set
            {
                this.ModifyTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FreeSCADA.CLServer.ChannelStatusFlags Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelStatusFlags", Namespace="http://schemas.datacontract.org/2004/07/FreeSCADA.CLServer")]
    public enum ChannelStatusFlags : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bad = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotUsed = 65535,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChannelInformationRetriever")]
public interface IChannelInformationRetriever
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelInformationRetriever/GetChannels", ReplyAction="http://tempuri.org/IChannelInformationRetriever/GetChannelsResponse")]
    FreeSCADA.CLServer.ChannelInfo[] GetChannels();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelInformationRetriever/GetChannelsCount", ReplyAction="http://tempuri.org/IChannelInformationRetriever/GetChannelsCountResponse")]
    long GetChannelsCount();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelInformationRetriever/GetChannel", ReplyAction="http://tempuri.org/IChannelInformationRetriever/GetChannelResponse")]
    FreeSCADA.CLServer.ChannelInfo GetChannel(long index);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IChannelInformationRetrieverChannel : IChannelInformationRetriever, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ChannelInformationRetrieverClient : System.ServiceModel.ClientBase<IChannelInformationRetriever>, IChannelInformationRetriever
{
    
    public ChannelInformationRetrieverClient()
    {
    }
    
    public ChannelInformationRetrieverClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ChannelInformationRetrieverClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChannelInformationRetrieverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChannelInformationRetrieverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FreeSCADA.CLServer.ChannelInfo[] GetChannels()
    {
        return base.Channel.GetChannels();
    }
    
    public long GetChannelsCount()
    {
        return base.Channel.GetChannelsCount();
    }
    
    public FreeSCADA.CLServer.ChannelInfo GetChannel(long index)
    {
        return base.Channel.GetChannel(index);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataRetriever", CallbackContract=typeof(IDataRetrieverCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IDataRetriever
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataRetriever/RegisterCallback")]
    void RegisterCallback(string channelId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataRetriever/SetChannelValue")]
    void SetChannelValue(string channelId, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRetriever/GetChannelState", ReplyAction="http://tempuri.org/IDataRetriever/GetChannelStateResponse")]
    FreeSCADA.CLServer.ChannelState GetChannelState(string channelId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDataRetrieverCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataRetriever/ValueChanged")]
    void ValueChanged(string channelId, FreeSCADA.CLServer.ChannelState state);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDataRetrieverChannel : IDataRetriever, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DataRetrieverClient : System.ServiceModel.DuplexClientBase<IDataRetriever>, IDataRetriever
{
    
    public DataRetrieverClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public DataRetrieverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public DataRetrieverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataRetrieverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataRetrieverClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void RegisterCallback(string channelId)
    {
        base.Channel.RegisterCallback(channelId);
    }
    
    public void SetChannelValue(string channelId, string value)
    {
        base.Channel.SetChannelValue(channelId, value);
    }
    
    public FreeSCADA.CLServer.ChannelState GetChannelState(string channelId)
    {
        return base.Channel.GetChannelState(channelId);
    }
}
