//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSCADA.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSCADA.Designer.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver.
        /// </summary>
        internal static string ArchiverItemName {
            get {
                return ResourceManager.GetString("ArchiverItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot; &gt;
        ///      &lt;Viewbox&gt;
        ///        &lt;Border BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;#FF0000FF&quot; Name=&quot;bdr&quot;&gt;
        ///          &lt;StackPanel Orientation=&quot;Vertical&quot;&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Name}&quot; Name=&quot;txt1&quot; Margin=&quot;0,0,10,0&quot; ToolTip=&quot;{Binding Path=Type}&quot; /&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Value}&quot; Name=&quot;txt2&quot; Margi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChannelDefaultTemplate {
            get {
                return ResourceManager.GetString("ChannelDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels Tree.
        /// </summary>
        internal static string ChannelsItemName {
            get {
                return ResourceManager.GetString("ChannelsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CommandCopyDescription {
            get {
                return ResourceManager.GetString("CommandCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CommandCopyName {
            get {
                return ResourceManager.GetString("CommandCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to clipboard.
        /// </summary>
        internal static string CommandCutDescription {
            get {
                return ResourceManager.GetString("CommandCutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CommandCutName {
            get {
                return ResourceManager.GetString("CommandCutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group selected items.
        /// </summary>
        internal static string CommandGroupDescription {
            get {
                return ResourceManager.GetString("CommandGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string CommandGroupName {
            get {
                return ResourceManager.GetString("CommandGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        internal static string CommandPasteDescription {
            get {
                return ResourceManager.GetString("CommandPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string CommandPasteName {
            get {
                return ResourceManager.GetString("CommandPasteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string CommandRedoDescription {
            get {
                return ResourceManager.GetString("CommandRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string CommandRedoName {
            get {
                return ResourceManager.GetString("CommandRedoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string CommandUndoDescription {
            get {
                return ResourceManager.GetString("CommandUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string CommandUndoName {
            get {
                return ResourceManager.GetString("CommandUndoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove grouping from curently selected item.
        /// </summary>
        internal static string CommandUngroupDescription {
            get {
                return ResourceManager.GetString("CommandUngroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnGroup.
        /// </summary>
        internal static string CommandUngroupName {
            get {
                return ResourceManager.GetString("CommandUngroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XAML code of current document.
        /// </summary>
        internal static string CommandXamlViewDescription {
            get {
                return ResourceManager.GetString("CommandXamlViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML representation.
        /// </summary>
        internal static string CommandXamlViewName {
            get {
                return ResourceManager.GetString("CommandXamlViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string CommandZoomDescription {
            get {
                return ResourceManager.GetString("CommandZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string CommandZoomInDescription {
            get {
                return ResourceManager.GetString("CommandZoomInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string CommandZoomInName {
            get {
                return ResourceManager.GetString("CommandZoomInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string CommandZoomName {
            get {
                return ResourceManager.GetString("CommandZoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string CommandZoomOutDescription {
            get {
                return ResourceManager.GetString("CommandZoomOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string CommandZoomOutName {
            get {
                return ResourceManager.GetString("CommandZoomOutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeSCADA 2 files (*.fs2)|*.fs2|All files (*.*)|*.*.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML  files (*.xaml)|*.xaml|svg files (*.svg)|*.svg|All files (*.*)|*.*.
        /// </summary>
        internal static string FileImportDialogFilter {
            get {
                return ResourceManager.GetString("FileImportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select trajectory object 
        ///    (line,rectangle,ellipse).
        /// </summary>
        internal static string HelperSelectingToolTooltip {
            get {
                return ResourceManager.GetString("HelperSelectingToolTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        internal static string MainWindowName {
            get {
                return ResourceManager.GetString("MainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - Designer.
        /// </summary>
        internal static string MainWindowNameEx {
            get {
                return ResourceManager.GetString("MainWindowNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        internal static string SchemasItemName {
            get {
                return ResourceManager.GetString("SchemasItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Edit Tool.
        /// </summary>
        internal static string ToolActionEdit {
            get {
                return ResourceManager.GetString("ToolActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Tool.
        /// </summary>
        internal static string ToolButton {
            get {
                return ResourceManager.GetString("ToolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentControl Tool.
        /// </summary>
        internal static string ToolContentControl {
            get {
                return ResourceManager.GetString("ToolContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls Tools.
        /// </summary>
        internal static string ToolControlsGroupName {
            get {
                return ResourceManager.GetString("ToolControlsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Tools.
        /// </summary>
        internal static string ToolEditorGroupName {
            get {
                return ResourceManager.GetString("ToolEditorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse Tool.
        /// </summary>
        internal static string ToolEllipse {
            get {
                return ResourceManager.GetString("ToolEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Tools.
        /// </summary>
        internal static string ToolGrphicsGroupName {
            get {
                return ResourceManager.GetString("ToolGrphicsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline Tool.
        /// </summary>
        internal static string ToolPolyline {
            get {
                return ResourceManager.GetString("ToolPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBar Tool.
        /// </summary>
        internal static string ToolProgressbar {
            get {
                return ResourceManager.GetString("ToolProgressbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Tool.
        /// </summary>
        internal static string ToolRectangle {
            get {
                return ResourceManager.GetString("ToolRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollBar Tool.
        /// </summary>
        internal static string ToolScrollbar {
            get {
                return ResourceManager.GetString("ToolScrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Tool.
        /// </summary>
        internal static string ToolSelection {
            get {
                return ResourceManager.GetString("ToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Tool.
        /// </summary>
        internal static string ToolSlider {
            get {
                return ResourceManager.GetString("ToolSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox Tool.
        /// </summary>
        internal static string ToolTextbox {
            get {
                return ResourceManager.GetString("ToolTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {unsaved project file}.
        /// </summary>
        internal static string UnsavedProjectName {
            get {
                return ResourceManager.GetString("UnsavedProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UntitledSchema {
            get {
                return ResourceManager.GetString("UntitledSchema", resourceCulture);
            }
        }
    }
}
